# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 50a34d8f09febaeb6f1b54a4d60a90a1636fc240807bc78e52d1540fa47f221ba3f177ccae4a19e59b01eac125fe38ea669c4e7879aa45e8e922747a83f70fd0

test:
  secret_key_base: 905691993bf2a862d961c7e3bcc622005879f14c171ffca68b427a5728bab6aa3d415507932f513cbd779345d1512c173f486ef7ebb4b4fb97fe100b4c74f1df

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
